# Generated by Django 4.2 on 2025-01-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buku",
            fields=[
                ("idbuku", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=255)),
                ("stok", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Penerbit",
            fields=[
                ("idpenerbit", models.AutoField(primary_key=True, serialize=False)),
                ("nama", models.CharField(max_length=255)),
                ("alamat", models.CharField(max_length=255)),
                ("nohp", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="BukuMasuk",
            fields=[
                ("idtrans", models.AutoField(primary_key=True, serialize=False)),
                ("jumlah", models.IntegerField()),
                (
                    "idbuku",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siperpus_app.buku",
                    ),
                ),
                (
                    "idpenerbit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="siperpus_app.penerbit",
                    ),
                ),
            ],
        ),
    ]
