# Generated by Django 4.2 on 2025-01-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siperpus_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="buku",
            name="harga",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="buku",
            name="stok",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="bukumasuk",
            name="jumlah",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
